version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-codedeploy
permissions:
  - object: /home/ubuntu/aws-codedeploy/deploy_hooks
    mode: 755
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 1200
      runas: root
  AfterInstall:
    - location: scripts/server-prep.sh
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 1200
      runas: root